### ISSUE TITLE
Mystery Fish enchantment activates when fishing entities?

### ISSUE THREAD

**Issue by GentlemanCheesy** [Geolykt/EnchantmentsPlus#103]
Mystery fish can be spammed by the user on entities to spawn in extra mystery fish related entities. This allows for players to abuse it for easier wet sponges and other items. I believe it should only spawn fish entities after successfully catching a fish, not a entity.

**Comment by Geolykt** [comment]
An interesting (and easily solvable) error on my part. Thanks for pointing that out
