### ISSUE TITLE
make incompatibilities configurable

### ISSUE THREAD

**Issue by CodeStrike84** [Geolykt/EnchantmentsPlus#104]
can you add unsafe enchants so we can add enchants that shouldn't normally be possible that would be a cool feature

**Comment by Geolykt** [comment]
What do you consider as "unsafe"? Do you mean that the admin enchantments should be obtainable via the enchantment table when the config option is switched or do you mean something else entirely?

**Comment by CodeStrike84** [comment]
that and you can add Enchants that don't work together like gust and rainbow slam

**Comment by Geolykt** [comment]
Ah yeah, allowing to make incompatibilities configurable has been planned, but was never realized because of the slight refractor is would require. Will eventually implement it though

**Comment by CodeStrike84** [comment]
ok

**Comment by Geolykt** [comment]
Turns out it was already implemented with 4.0.0, but shh
