### ISSUE TITLE
3.1.6 (user using version 1.16) Cool time  error. (I can't apply it.)

### ISSUE THREAD

**Issue by slswkrh0000** [Geolykt/EnchantmentsPlus#106]
Hello, I am a user who used Zenchantments. As 1.16 support was not available, I transferred to a plug-in after March 2021.

I'm satisfied, but I have a question.
Each magic cool time does not apply. Is it revised after version 4.0.0?
Why is 1.16 recommended not to use 4.0.0?

+I'm worried if it's translated properly because it's a translator.
If it is simply my problem that cool time does not apply in version 3.1.6, I would like to know the reason.
If you need to update it to a higher version, please tell me how to do it.
Thank you.

**Comment by Geolykt** [comment]
The last time cooldowns were refractored was in 3.0.0, so it could very well be that I did some messups back then.
4.+ should not be used in 1.16 because the default config files are for 1.17, so you'll get a lot of config spam at startup because blocks are not found.

**Comment by slswkrh0000** [comment]
Then, is there any way to implement cool down in version 3.1.6?

**Comment by Geolykt** [comment]
I'll first need to see whether that is even a bug or a user error which can take quite a while because I haven't played minecraft for ages and I simply lack the motivation to even work on this plugin

**Comment by Geolykt** [comment]
I cannot reproduce this bug, are you sure you set it in the config file for the given world?

**Comment by slswkrh0000** [comment]
I attached it below. Also, we recently updated the plug-in to 1.17 version.

[world.zip](https://github.com/Geolykt/EnchantmentsPlus/files/7683677/world.zip)
?

**Comment by Geolykt** [comment]
hm, would need to check whether those enchantments actually support cool-downs right now; will reopen the issue for the time being

**Comment by slswkrh0000** [comment]
ok Thank you. I hope the problem will be solved soon.

**Comment by eyesonme1212** [comment]
Same error as me!

**Comment by Geolykt** [comment]
Yeah sorry, while I know that a fix would be rather straightforward (given that the checks are simply missing hehe) I am not sure when I will find the motivation to fix it... Perhaps I'm even better off shelving the plugin as a whole

**Comment by eyesonme1212** [comment]
Oh, I can't do that. Don't give up T.T It's a good plugin... There is no replacement plugin

**Comment by Geolykt** [comment]
Cannot reproduce.
Keep in mind that for some enchantments there is no real use in having a cooldown (e.g. Jump since it is just a potion effect being applied on the player) and that the cooldown is in ms and not in ticks.
