### ISSUE TITLE
Vortex enchant eats EXP that should be used for items with mending.

### ISSUE THREAD

**Issue by GentlemanCheesy** [Geolykt/EnchantmentsPlus#108]
Latest version has the above issue which I found inconvenient enough to write about here. Vortex renders mending useless if on your main weapon in most early game EXP farms.

My suggested change is to disable vortex for EXP while you have 1 or more item(s) with mending and durability to be repaired.

Thank you in advanced and happy holidays!

**Comment by Geolykt** [comment]
That is an interesting issue, however thankfully a player can use `/ench disable Vortex` to temporarily kill the functionality of the enchantment and the `/ench enable Vortex` re-enables it's functionality.

I will not close this issue however as Vortex was never made with Mending in mind (most enchantments in this plugin predate 1.9) which should obviously be accounted for
