### ISSUE TITLE
CoreProtect dependency

### ISSUE THREAD

**Issue by alexchandel** [Geolykt/EnchantmentsPlus#110]
I get this warning when using EnchantmentsPlus with CoreProtect:

```
[14:49:05 WARN]: [Enchantments_plus] Loaded class net.coreprotect.CoreProtectAPI from CoreProtect v20.4 which is not a depend, softdepend or loadbefore of this plugin.
```

Should you be declaring an optional or soft dependency on CoreProtect?  Look at how [Magic](https://github.com/elBukkit/MagicPlugin) does optional/soft dependencies on a dozen different plugins.

**Comment by Geolykt** [comment]
Seems like I forgot to add coreprotect in the soft-depend category. Will be fixed with the next release
