### ISSUE TITLE
No enchantment types

### ISSUE THREAD

**Issue by oguh43** [Geolykt/EnchantmentsPlus#12]
latest craftbukkit, no enchantment types are displayed

**Comment by Geolykt** [comment]
Thanks for the Bug report, however a bit more information is needed so it can be processed accordingly.

a)
 What is the current Plugin Version
b)
  What were the previous plugin Versions?
c)
  What is the exact Server Version (CB is updated multiple times a day — LATEST is a very inacurate description)?
d)
  When was the patches.yml/magicCompat.yml last reset?
e)
  If the Plugin doesn't use default settings, which changes were made to them? 

As a Sidenote, Craftbukkit is NOT supported, while we will respond to issues made by CB-server owners, we will not patch any issues that only affect CB. Reason behind that is that CB is rather hard to obtain legally (CB and Spigot cannot be redistributed, and md_5 makes great atfempts at lowering it's usage) and If you are already using BuildTools, consider building Spigot instead. If you use a host that provides CB, consider using Spigot or Paper instead.

**Comment by oguh43** [comment]
Version 2.1.2 loads, however the list is still empty. Btw the decimal enchantment chance means %? Is 1.0 100% or 1%?

**Comment by oguh43** [comment]
bukkit version: 890130b

**Comment by Geolykt** [comment]
I'm not sure about about what it exactly does, but 0 is unobtainable and 1 is default, I think it is pretty linear, I however doubt that the number is a percentage, but just a multiplier

**Comment by Geolykt** [comment]
Did you use the plugin once before you updated to 2.1.2?

**Comment by oguh43** [comment]
> Did you use the plugin once before you updated to 2.1.2?

Yes, I tried enchanting by command and the enchantments work, however, I also enchanted 5 hotbars of tools/armours and got nothing. Also when using the command, the added enchantment doesn't have custom style, nor lore. But that was broken in enchantments too.

**Comment by Geolykt** [comment]
Details? If you used a 2.0.x or 1.x.x Version, then delete the magicCompat.yml file, If the issue is not resolved, come back to mr

**Comment by oguh43** [comment]
a) the file  was deleted and issue not solved
b) I don't understand what "come back to mr" means
3) probably a bukkit issue, thanks for your time :)

**Comment by Geolykt** [comment]
I'll try to replicate it, but given that I may misunderstand with what you mean with enchantment types, I'm not totally sure

**Comment by oguh43** [comment]
![image](https://user-images.githubusercontent.com/13382592/96460076-20e58480-1223-11eb-9b71-3a7d8c6a7e9b.png)

**Comment by Geolykt** [comment]
This is expected behaviour when invoked with an empty Hand.
`/ench list` lists all applicable enchantments for the tool held in the main hand, so If you are holding AIR right now, nothing can be applied in it.
If you are holding something different (A chestplate for example) though the question is valud

**Comment by oguh43** [comment]
> This is expected behaviour when invoked with an empty Hand.
> `/ench list` lists all applicable enchantments for the tool held in the main hand, so If you are holding AIR right now, nothing can be applied in it.
> If you are holding something different (A chestplate for example) though the question is valid

This happens when holding anything, but this was done with an iron shovel in hand.

**Comment by scottyboii** [comment]
I'm also experiencing this issue, tried using shovels and pickaxes. Both with and without custom enchants already. 

**What is the current Plugin Version**
2.1.2

**What were the previous plugin Versions?**
First time using.

**What is the exact Server Version?**
git-Paper-184 (MC: 1.16.2)

**When was the patches.yml/magicCompat.yml last reset?**
Today

**If the Plugin doesn't use default settings, which changes were made to them?**
Default

**Screenshots?**
![image](https://user-images.githubusercontent.com/32883419/96480292-f64ef800-1231-11eb-9753-a26cc83807c2.png)

**Comment by Geolykt** [comment]
The issue was confirmed and was found to be a symptom of another bigger issue

**Comment by oguh43** [comment]
Unless the new release isn't published yet and updating the MagicCompat.yml should solve the issue, its still broken.

**Comment by Geolykt** [comment]
the update is released on github now @oguh43

**Comment by oguh43** [comment]
Thanks, the list commands now displays correctly, but I still can't get any enchant.

**Comment by Geolykt** [comment]
I'll look into it tomorrow

**Comment by oguh43** [comment]
> I'll look into it tomorrow

Thanks :)

**Comment by Geolykt** [comment]
@oguh43 Issue is know and was fixed in the last commit - update should be out soon

**Comment by oguh43** [comment]
> @oguh43 Issue is know and was fixed in the last commit - update should be out soon

Thanks!

**Comment by Geolykt** [comment]
@oguh43 Released!
