### ISSUE TITLE
Cooldown

### ISSUE THREAD

**Issue by Restland** [Geolykt/EnchantmentsPlus#120]
I've added a cooldown to several Custom Enchants but that doesn't seem to work, is it broken or there is something wrong by my side.

**Comment by Geolykt** [comment]
There were already a few issues that were opened that described issues like that. What enchantments in specific are affected by this bug?

I sadly haven't migrated to microsoft yet, so it takes a while till I'll get the ball rolling again - so have patience

**Comment by Restland** [comment]
Its sure doesn't work with fireworks I can check for the others tomorrow.

**Comment by Restland** [comment]
All bow ones doesnt work, persephone  and shred aswell. This only the ones that I have a  cooldown one and it doesnt seem to work.

**Comment by Geolykt** [comment]
I cannot reproduce it. Hopefully it is a bug that was fixed more or less accidentally a while ago.

I'll push out a release now and hopefully it will magically solve itself.

**Comment by Restland** [comment]
It still doesnt seem to work... :/

**Comment by Geolykt** [comment]
Did you set the cooldowns in ticks or seconds by any chance? If so then that explains it, otherwise I cannot really explain your issue

**Comment by Restland** [comment]
Its written like that :

- Fireworks:
    Probability: 1.0
    Tools: Bow
    Name: Fireworks
    Max Level: 4
    Cooldown: 4
    Power: 1.0

**Comment by Geolykt** [comment]
That explains it. Cooldowns are in milliseconds
