### ISSUE TITLE
Fire enchantment doesnt work correctly

### ISSUE THREAD

**Issue by TerslenK** [Geolykt/EnchantmentsPlus#126]
When i try to break nether gold ore it drops nuggets instead of gold ingot

**Comment by Geolykt** [comment]
Yeah, that is working as intended iirc.
If smelting nether gold ore yields ingots it becomes a bug however, but I do not think that that is default behaviour

**Comment by SonicCraft** [comment]
Um thats not what happens when you smelt nether gold ore. You actually get an ingot. If you break it normally without a smelting enchantment you get nuggets.

**Comment by TerslenK** [comment]
^ thats why i opened this issue
![image](https://user-images.githubusercontent.com/88115382/167265171-337c97ec-7da7-4ad4-b0b7-12594dbe11fe.png)

**Comment by TerslenK** [comment]
@Geolykt

**Comment by Geolykt** [comment]
Yeah that is true, still technically working as intended given that it only smelts the outputs and not the broken blocks themselves, but I think there is some space for interpretating the meaning of the enchantment differently - so it might be get a toggle for the different meanings.

**Comment by TerslenK** [comment]
ah okay
