### ISSUE TITLE
Slowness still appearing without the weight enchantment

### ISSUE THREAD

**Issue by OmikronOverload** [Geolykt/EnchantmentsPlus#13]
We were Testing some Enchantments, as we went over the weigth enchantment he put on the boots and since then he is slow forever. And yes even without the boots, affect still applies. 

Know any fix for this?

**Comment by Geolykt** [comment]
It's probably because of a refractor I did a while ago, I'll attempt to recreate it when I can

**Comment by Geolykt** [comment]
It should be noted that even with the patch the player will see a permanent slowness effect, this can be removed by resetting the walking/flying speed, which can be performed via plugins like Essentials
