### ISSUE TITLE
No enchants work

### ISSUE THREAD

**Issue by ShrimpScript** [Geolykt/EnchantmentsPlus#131]
My native server version is 1.17.1 spigot, I have latest version of plugin, but when I use /ench (nameofenchant) on any items, it says "the enchantment cannot be applied to your item" ex: I use /ench burst on crossbow or bow and it says that message

**Comment by Geolykt** [comment]
That is extremely odd. Are there are error in log? Especially at startup those error are important.
Though it could always be that I bricked 1.17.1 support, but I doubt that given that internals have not changed for some time now.
Also would be a good to have a look at your `world.yml` and `magicCompat.yml` files - chances are those are outdated (especially latter)
