### ISSUE TITLE
Siphon fix

### ISSUE THREAD

**Issue by CrimsonSerpent5** [Geolykt/EnchantmentsPlus#132]
Siphon seems to make mobs constantly take damage after a couple of hits.

**Comment by Geolykt** [comment]
That is a pretty strange bug.
Could you post a video or something so I have a better clue on what I am searching for?

**Comment by Geolykt** [comment]
Can't reproduce.

**Comment by CrimsonSerpent5** [comment]
I can reproduce give me some time
