### ISSUE TITLE
Disabling enchantments in the table

### ISSUE THREAD

**Issue by krakitynsk** [Geolykt/EnchantmentsPlus#138]
I did not find the option to disable custom enchantments in the enchantment table, is there such a possibility in principle?

**Comment by Geolykt** [comment]
Yes - it is possible to do so!

In the world.yml (and probably in the nether.yml and the world_the_end.yml too) you can set the probability of each enchantment to `0.0` (not `-1.0` though!)

There is also the possibility to do it through setting the global `enchant_rarity` but alas it has been too long of a time to remember what value you need to set it to
