### ISSUE TITLE
Shred not working

### ISSUE THREAD

**Issue by scottyboii** [Geolykt/EnchantmentsPlus#14]
Shred enchant not working on both pickaxes and shovels (tried iron and diamond), tried various levels as well.
/ench info shows that the tool has shred on it but no blocks are broken around it.

**What is the current Plugin Version**
2.1.2

**What were the previous plugin Versions?**
First time using this plugin, however we had Zenchantments before

**What is the exact Server Version?**
git-Paper-184 (MC: 1.16.2

**When was the patches.yml/magicCompat.yml last reset?**
Reset them just now.

**If the Plugin doesn't use default settings, which changes were made to them?**
No edits.

Screenshots?
n/a

**Comment by Geolykt** [comment]
Where the hell did all this influx come from? But this should be solved rather soon, given that your Paper version is so old I highly assume that it's a logical issue (newer builds tend to break this plugin for some reason)

**Comment by Geolykt** [comment]
The issue was confirmed and was found to be a symptom of another bigger issue
