### ISSUE TITLE
[suggestion] Configurable range for "Sonic shock" and "Spike"

### ISSUE THREAD

**Issue by Uboaaaaa** [Geolykt/EnchantmentsPlus#17]
Hi! I'm just thinking that some of the enchantments have much larger entity detection range compared to original Zenchantment...... _as much as I can remember?_ "Sonic Shock" and possibly "Spike" had a greater range compared to the Zenchantment in my memory where one has to accurately stomp onto or crush into the targets. I still prefer them to be smaller so there's less chance of damaging unwanted entities around the player. Would it be convenient to add a configuration for this?

**Comment by Geolykt** [comment]
Would be possible, however the value was unchanged from the original plugin
