### ISSUE TITLE
Can not use grindstone to remove enchantment.

### ISSUE THREAD

**Issue by Toby-C** [Geolykt/EnchantmentsPlus#18]
sorry for my bad english.
Just like title say, all of enchantment of this plugin can not remove,
is this a bug or anything I need to change?

**Comment by Geolykt** [comment]
It makes sense since that class hasn't been looked at in ages.
Either way, what's you plugin and server version? I'd also like to know whether you are still running on default configurations

**Comment by Toby-C** [comment]
I use paper 1.16.3 and the plugin version is 2.1.5d.
all of this plugin still running on default configuration.

**Comment by Geolykt** [comment]
Well, that means it's likely my bad, thanks for reporting the issue, it'll take a while to get it fix though as there are quite a lot of different issues that need to be adressed right now

**Comment by Toby-C** [comment]
thanks for your help.
So I'll leave it to you. Thanks.
