### ISSUE TITLE
Disable enchantment books on anvil if the tool is not supported for this enchantment.

### ISSUE THREAD

**Issue by Uboaaaaa** [Geolykt/EnchantmentsPlus#19]
I'd like to sell some zenchantment books in my smol SMP server so people can have fun with them. However soon after the shop's open for business, people had Anthropomorphism on chestplates, Fire on sword, Spread on shovel, Reaper on hoe and, for some reason, Stream on bucket.

So I think maybe add the check when applying enchantments on anvil, which disables enchanting if the tool type is unsupported for the enchantment?

**Comment by Geolykt** [comment]
This is actually a bug that should be fixed
