### ISSUE TITLE
No Plugin Feedback / does not work

### ISSUE THREAD

**Issue by OmikronOverload** [Geolykt/EnchantmentsPlus#21]
Hello,

Im on Paper-131, for 1.16.1 and im using the latest EnchantmentsPlus 2.2.1.
The page says it should work for 1.16.1, but not under.(If my understanding is correct)
Problem is, that the Plugin gives no Feedback and doesnt work, but is active in the plugin list.

Cheers
OmikronOverload

**Comment by Geolykt** [comment]
Any exceptions on startup?
On another notice, I'm pretty sure we support everything from 1.15 upwards, just requires a bit of tweaking the config files

**Comment by OmikronOverload** [comment]
No exceptions, everything working fine.
What do mean by tweaking?

**Comment by Geolykt** [comment]
There's no tweaking required if there are no exceptions, but with tweaking I meant the magicCompat.yml file.
Does `/ench version` show anything?

**Comment by OmikronOverload** [comment]
Oooooooooooooh, you have to enable it first.
Dang, im dumb...
/ench never worked before, now it does. I always used /enchantments_plus:ench, ofcourse there is no feedback :|.
Well, i guess thats that, now its giving feedback with only /ench

**Comment by Geolykt** [comment]
wdym with enable?

**Comment by OmikronOverload** [comment]
[14:16:58] [Server thread/INFO]: OmikronOverload issued server command: /ench enable all

**Comment by Geolykt** [comment]
Strange, well, one more reason to remove that feature.
I'll close the issue since it appears to be fixed

**Comment by OmikronOverload** [comment]
Yes, thanks for helping 👍
