### ISSUE TITLE
Could not pass event BlockDispenseEvent to Enchantments_plus v2.2.2

### ISSUE THREAD

**Issue by bojaspie** [Geolykt/EnchantmentsPlus#26]
Hi on my 1.16.4 server runned by paper for the first 10 minutes of the server the plugin works fine until it starts spamming my console with
Could not pass event BlockDispenseEvent to Enchantments_plus v2.2.2
i rly dont know what to do in this case i've saw that i need to add some code in it but i rly dont know how to do that may you please help me?
thanks

**Comment by scottyboii** [comment]
Look in your log files, there will be a longer, full error at the start. Find that and send it here.

(Ctrl+f will help)

**Comment by bojaspie** [comment]
https://pastebin.com/mXUBZM9x

**Comment by Geolykt** [comment]
This probably has to do with your configuration having issues.
Make sure that all probabillities are in the format `123.456`, the `.` has to be there either way, even if there are only leading 0's.

It probably has to do something with the laser enchantment (could also be any other enchantment to be honest) and I highly assume that this is done knowingly to lag the server.

**Comment by bojaspie** [comment]
i dont think it was made to lag the server the one who made it is rly dumb in these stuff so i assume i have to change all disabled enchantments to -1.0?

**Comment by Geolykt** [comment]
Yep, -1 won't work.
I'll mark the issue as closed, but in case that you think that doesn't resolve the issue, feel free to notify me so it can be reopened and looked at again
