### ISSUE TITLE
(Suggestion) Make the Vortex enchantment work on all items

### ISSUE THREAD

**Issue by Special70** [Geolykt/EnchantmentsPlus#27]
This would be helpful for people who would use any type of item as a weapon. Axes, flowers, sticks, it would be great if the vortex enchantment works on all items not just in swords and bows

**Comment by Geolykt** [comment]
While the axe suggestion makes sense, I do not believe that it makes any sense to make Vortex work on any other item.
However please note that I'm only altering the default settings, in actuality this is a bit different and can be freely reverted back or changed by any admin to encompass all items
