### ISSUE TITLE
Can't apply book to tools,weapon and armor in survival

### ISSUE THREAD

**Issue by Anfieldgtv** [Geolykt/EnchantmentsPlus#28]
Version :  2.2.2 (according to ingame command)
I have done no changes to configs or anything
Server: CraftBukkit version git-spigot-628435a-72c5e74 (MC:1.16.4)

**Comment by Anfieldgtv** [comment]
![image](https://user-images.githubusercontent.com/76686857/103209281-4682be80-4935-11eb-9e95-c74f6c78c245.png)

**Comment by Anfieldgtv** [comment]
and also I can apply enchants in creative but not survival
is it something about permission?

**Comment by Geolykt** [comment]
Duplicate of #24 .
I will look at what I can do, probably by using the legacy merger instead for spigot servers
