### ISSUE TITLE
NetherStep rarely/barely works

### ISSUE THREAD

**Issue by TehBooris** [Geolykt/EnchantmentsPlus#29]
Can't seem to get netherstep to work properly, no soul sand spawns or if it does it just flickers constantly. Server is on 1.16.4 running Paper

Video of bug [here](https://youtu.be/j-ONi-bWc4E)

**Comment by TehBooris** [comment]
[Example of the flickering](https://youtu.be/qy9BTC9dJp4)

**Comment by Geolykt** [comment]
Thanks for the report, I'll look into it.
Which version of the plugin are you using?
 (don't say latest - we have two latest releases)

**Comment by TehBooris** [comment]
3.0.0-rc.2
