### ISSUE TITLE
Enchantments making items disappear after first use

### ISSUE THREAD

**Issue by TehBooris** [Geolykt/EnchantmentsPlus#30]
Enchantments that affect a wide area make the tool disappear on the first use a lot of the time, noticed this a lot with Shred, Harvest and Spread.

**Comment by TehBooris** [comment]
Paper 1.16.4, plugin version 3.0.0-rc.3

**Comment by scottyboii** [comment]
Would this not be because of durability being used per block break? So if shred breaks 40 blocks it takes 40 durability?

I had similar issue but adding the ethereal enchantment or unbreakable nbt seems to function fine.

**Comment by Geolykt** [comment]
No it probably has to do with the optimisations done in 3.0.0-rc.2/rc.3, I'll what exactly causes this, I suspect an inverted conditional.

Tested to happen with reveal
