### ISSUE TITLE
How to make it so all items can be applied with the vortex enchantment

### ISSUE THREAD

**Issue by Special70** [Geolykt/EnchantmentsPlus#31]
I don't know how and I need it since I'm using majority of the game's items as weapon types

**Comment by Geolykt** [comment]
You can set the Tools to `All` in the per-world-configurations for the Vortex enchantment. However in this case it's not absolutely everything (only armor and tools and weapons), but this list can be altered in the magic compatibility file.
Just note that this may have grave consequences and might even allow for dupes (in combination with bind), so I don't really recommend it. I might add a category that is actually absolutely everything, but I don't think it has much of a priority right now
