### ISSUE TITLE
Plugin Not Loading

### ISSUE THREAD

**Issue by FoggyJarl** [Geolykt/EnchantmentsPlus#35]
I've downloaded the latest file but, every time I try and put it into my plugins folder and restart my server, no config file is created and I can't use any commands or get any enchantments. I assume the commands are the same as Zenchantment's commands but, nothing else is working. I don't know if it's something wrong just for me or what but, I've tried everything I can think of.

**Comment by levtey** [comment]
Are you on Java 11? As stated in bold text in the description:
![image](https://user-images.githubusercontent.com/60494179/105561838-d0237300-5ccc-11eb-9349-91e42d034567.png)

**Comment by Geolykt** [comment]
Did you resolve the issue by changing Java or the plug-in version or is this still an issue even after you verified the correct version?
If you still have the issue, it is helpful (and even imperative) to provide logs as I cannot help you otherwise.
