### ISSUE TITLE
reveal summons shulkers

### ISSUE THREAD

**Issue by Ltghavoc** [Geolykt/EnchantmentsPlus#41]
The reveal enchant has started summoning shulkers after the ores are loose their glow.  i don't know what else to even say there are no errors or anything just a bunch of shulkers get summoned.

**Comment by Ltghavoc** [comment]
happens on 3.0.0  and 3.1.2

**Comment by Geolykt** [comment]
I'll look into it. But the fact they spawn is intended, that they persist not.
Are you using a modified client or anything or how do you know that they are spawned?

**Comment by Geolykt** [comment]
I was unable to reproduce it, however I have seen a few issues when it comes to removing the shulkers, most noteably explosions, but also the fill and setblock commands will leave them exposed. However in every case they were cleared after a small delay as they do not persist forever.I accidentally tested it with the wrong version (v2.2.4) and idn't notice that, ooops. However even in 3.1.2 it's the same behaviour

**Comment by Ltghavoc** [comment]
so a thought occurred that it may be because they are being stacked by stackmob

**Comment by Geolykt** [comment]
I'll look if I can integrate this plugin in that plugin, if that is not possible I guess you might need to create an Issue to disable stacking of invincible mobs (if that is not already an option in the plugin's settings).

If I may ask for easier integration on my side, what exact plugin are you using?

**Comment by Ltghavoc** [comment]
I dont know that is an option but I can at least prevent shulkers from stacking which should fix it, if that really is the cause.

here is the plugin
https://www.spigotmc.org/resources/stackmob-enhance-your-servers-performance-without-the-sacrifice.29999/

**Comment by Geolykt** [comment]
I think I have found a "solution" to it, but it needs some testing. ~~However it will never see light as the plugin is not open source and as such I cannot distribute it and as such I cannot link to it as there is no way of obtaining it via Maven or anything without building it yourself (which is a hassle I do not want anyone to go into)~~ The plugin has added a license, which now allows me to put it in the mainline, whoo!

**Comment by Ltghavoc** [comment]
i see well at the very least I confirmed that exempting shulkers from stacking fixes the issue for my purposes at least.
