### ISSUE TITLE
Enchantments not combining correctly

### ISSUE THREAD

**Issue by chrismwiggs** [Geolykt/EnchantmentsPlus#42]
Just updated EnchantmentsPlus to 3.1.2 (paper 1.16.5) and I'm finding that combining books is not working correctly. 

Say you have two books, one with Piercing 1 and Longcast 1, and one book with Projectile Protection I and Long Cast I. When combining, I would expect to see Longcast 2 and Piercing and/or Projectile Protection (not sure with those two, but Longcast for sure). But Long cast is being dropped and I'm only able to get Piercing and  Projectile Protection, no matter the order added to the anvil. 

I have a max enchant limit of 2, which I assumed meant a max custon enchant of 2 per item, but something is going weird here either in the mix of vanilla + custom or adding like enchants.

**Comment by Geolykt** [comment]
This issue might have gotten fixed with 59586ab8acec03cb71ff069ce88f89fd3a72535d however it needs further testing to say for sure

**Comment by Geolykt** [comment]
Does this issue still persist for you?

(closing due to no response)
