### ISSUE TITLE
Plugin doesn't loading

### ISSUE THREAD

**Issue by nosooqua** [Geolykt/EnchantmentsPlus#44]
Startup error:
![image](https://user-images.githubusercontent.com/35642108/112004109-8f13d780-8b32-11eb-93ac-76a796abb761.png)

Java version: 
![image](https://user-images.githubusercontent.com/35642108/112004200-a2bf3e00-8b32-11eb-931a-5e7561b5ee6c.png)

Server core:
![image](https://user-images.githubusercontent.com/35642108/112004268-af439680-8b32-11eb-9fd1-735f50d7e186.png)

**Comment by Geolykt** [comment]
Strange, but I'll try to hotfix that ASAP
