### ISSUE TITLE
Bounce enchant triggering jump when walking on to a slime block

### ISSUE THREAD

**Issue by chrismwiggs** [Geolykt/EnchantmentsPlus#46]
The bounce enchant on boots, when you walk on to a slime block, forces you to jump without you actually pressing jump. It maintains the momentum like you'd expect, but just makes walking on slime blocks impossible. 

Paper 1.16.5
Enchants+ 3.1.4

**Comment by gecko10000** [comment]
I believe this is intended behavior.

**Comment by chrismwiggs** [comment]
Maybe worth rethinking then? The original docs describe it as maintaining momentum, which makes sense, but if that was the case you would have to jump first.

**Comment by Geolykt** [comment]
The enchantment is strange in many regards, for example it does not maintain momentum, it actively creates one; as far as I know sneaking will "resolve" this issue, which I currently find a fine compromise.
About the description of the enchantment, it probably needs to be redefined as I think it is too late to change how the enchantment works (I could make it configurable, but maintenance will haunt me later). Any suggestions on that?
