### ISSUE TITLE
Weight Enchant

### ISSUE THREAD

**Issue by Ijeioty** [Geolykt/EnchantmentsPlus#52]
It seems with the weight enchant it increases your damage from mobs for whatever reason.

**Comment by Geolykt** [comment]
Increasing the damage of mobs to the player would be unintended, but increasing the damage of the player to mobs is intended.
From a quick search it does not look if the player gets more damage from mobs, but I have to yet test this further

**Comment by Ijeioty** [comment]
Oh alright I was just confused because it doesn't say anything about increasing damage from mobs in the description of the enchant.
