### ISSUE TITLE
Stock enchantment not refilling hand

### ISSUE THREAD

**Issue by chrismwiggs** [Geolykt/EnchantmentsPlus#55]
Unless I am misunderstanding how the stock enchantment works, it appears to be broken. Trying it by putting a stack of stone in my inventory and putting 3 stone in my hot bar. Place the 3 stone and expected the stone from my inventory to be auto moved to my current slot., but no luck. Tried with the extra blocks in my hotbar too, still doesn't get moved over. Not in offhand either. 

Paper 1.16.5
Enchants+ 3.1.5

**Comment by Geolykt** [comment]
While looking at the code I cannot immediately spot the cause of the defined behaviour, however I did find a few unrelated issues concerning it, which I will take a look at (especially on whether it actually is a reason for caution).

To how Stock works, it will only refill when the stack is empty
