### ISSUE TITLE
Night Vision "flickering"

### ISSUE THREAD

**Issue by Uboaaaaa** [Geolykt/EnchantmentsPlus#60]
The potion effect granted by _Night Vision_ enchantment keeps disappearing and coming back, causing frequent flickering... Not very good for those with seizures.

Similar issue also happens on _Jump_.

**Comment by Geolykt** [comment]
I'll look into extending the duration of these effects; I was never able to test it in a high-ping environment, though this makes much sense

**Comment by Uboaaaaa** [comment]
In fact the night vision that's been granted has 30 seconds, and the flickering is caused by a sudden loss of the effect instead of it passing out on its own, so I believe there's something else causing the issue.

**Comment by Geolykt** [comment]
That is more interesting
