### ISSUE TITLE
Worldguard flag to restrict the use of all enchantments

### ISSUE THREAD

**Issue by chrismwiggs** [Geolykt/EnchantmentsPlus#61]
I keep running into issues where enchants shouldnt work in restricted areas (or I would want them to not work), like Fire and MysteryFish. Not sure how feasible it is, but it might be a good blanket solution to add a WorldGuard flag to deny the use of custom enchants entirely in the region. Gives server owners the control they probably want, in a survival server with lots of protected areas (spawns, shops, tutorials, etc). And stops having to chase specific weird edge cases!

**Comment by Geolykt** [comment]
The current implementation (which will be shipped in 3.1.6 that will ship in a few minutes) of this feature is a bit wonky at best given that it ignores region ownership and a lot more, but I would consider it "good enough" for mass-denying enchantment use.

If you experience any larger problems with it let me know
