### ISSUE TITLE
Unable to create kits with custom enchants on.

### ISSUE THREAD

**Issue by Restland** [Geolykt/EnchantmentsPlus#69]
Everytime I try to create a kit , or even add an item on a crate with custom enchant is shows up us lore: laser 1 for example. Any fix for that?

**Comment by gecko10000** [comment]
Well, the enchantments are displayed via lore: that is the way it is done in all custom enchant plugins. If you're using GoldenCrates, it has an option to set the display item to be different than the reward.

**Comment by Restland** [comment]
So lore, makes it work ?

**Comment by gecko10000** [comment]
It depends on the setting you have in the magicCompat.yml, but lore is the way custom enchantments are displayed to the player. If the enchant gatherer is using PersistentDataContainer, the removal of lore will most likely not affect the enchantments on the item, but the enchantments will not show to, and may confuse, the player. There is no other way to show the enchantments to the player unless they have a client-side mod.

**Comment by Restland** [comment]
alright thank you. the case can close now.
