### ISSUE TITLE
Paper Problems

### ISSUE THREAD

**Issue by Turtle-Chan** [Geolykt/EnchantmentsPlus#71]
So, I recently downloaded this plugin and upon placing it in my plugins folder and launching my PaperMC Server, I received this error.
`[09:10:25 ERROR]: Could not load 'plugins\enchantments-plus-3.1.6.jar' in folder 'plugins'`
The full startup log can be found [here](https://pastebin.com/CzZJuxsi).

**Comment by Turtle-Chan** [comment]
Ok, so I'm actually stupid.
I installed the wrong Java version.
Updated my Java installation, working now.
I am currently using [AdoptOpenJDK](https://adoptopenjdk.net/?variant=openjdk16&jvmVariant=hotspot). 
Looking forward to version 4.0.0!

**Comment by Geolykt** [comment]
It will still take a while till that one releases, though I hope to do it quickly given that it will be the one having to support 1.17 (though who knows maybe 1.17 will not be too bad so 2.x.x / 3.1.6 can handle it).

anyways, closing this issue since I guess that this was resolved
