### ISSUE TITLE
enchantments with potion effects do not work

### ISSUE THREAD

**Issue by YryUiaUif** [Geolykt/EnchantmentsPlus#77]
e.g bow enchants such as potion and toxic, it does not apply potion effects to user/target

**Comment by Geolykt** [comment]
I wasn't able to reproduce it (well, the reproduction steps were just to check whether it works on myself - which may alter how it works), could you provide better information?

**Comment by YryUiaUif** [comment]
Managed to find the issue, potion and toxic did not work with spectral arrows
