### ISSUE TITLE
[Error] Loading magic compatibillity file

### ISSUE THREAD

**Issue by FunkyNico** [Geolykt/EnchantmentsPlus#79]
Hey there, i was trying the plugin on to my server, but i got this issue:

https://hastebin.com/oyuzeyinoq.properties

My server is using: Paper version git-Paper-779 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT).
System Info: Java 16 (OpenJDK 64-Bit Server VM 16.0.1+9) Host: Windows 10 10.0 (amd64).

Plugins: ActionHealth, AngelChest, AureliumSkills, AuthMe, Bookshelf, ChestSort, Chunky, ChunkyBorder, CoreProtect, Elevator, Enchantments_plus, Essentials, EssentialsChat, EssentialsSpawn, eZProtector, FarmControl, FastAsyncWorldEdit (WorldEdit), FastLogin, Harbor, IllegalStack, LuckPerms, LWC, PlaceholderAPI, ProtocolLib, RHLeafDecay, SkinsRestorer, spark, SuperChairs, Vault, WorldEditSelectionVisualizer, WorldGuard

Greetings.

**Comment by Geolykt** [comment]
It would be good to know the plugin version (v4.0.0 is able to run on 1.16.5 but with heavy issues unless an older magic compat file is used).
It also appears that your hastebin link does not show anything so I cannot say anything further here.

**Comment by FunkyNico** [comment]
I have no problems with hastebin, anyways here i left the same error on other sites:

https://pastebin.com/1xAc7svq
https://paste.ubuntu.com/p/SttHr3rRMy/

I will download the v3.1.6 and use the magicCompat.yml file with the v4.0.0 to see if it works.

**Comment by Geolykt** [comment]
Thank you, it's an interesting edge case that I did not expect to happen. That being said it is likely easily fixable. Will fix it (soon-ish)
