### ISSUE TITLE
Grab bug

### ISSUE THREAD

**Issue by Restland** [Geolykt/EnchantmentsPlus#82]
Grab give a tons of xp when breaking a lot of ores.
The server also has 
Veinminer and wildstacker don't know if one of them cause the issue but 1.5-2 stack of coal can make up to 200 levels.

**Comment by Geolykt** [comment]
Doesn't happen during my test - heck using veinminer I went from level 12 to level 13 with a single stack - so I am seeing more of the opposite. Are you sure that grab is the cause?

**Comment by Restland** [comment]
I removed the grab enchant to make sure. Proof of it happening before.
![image](https://user-images.githubusercontent.com/84740054/124518250-a1b6d180-ddee-11eb-9d5e-64b0a9222228.png)

**Comment by Geolykt** [comment]
I'll try it again tomorrow - perhaps I will have better chances then

**Comment by Restland** [comment]
Can I send you a video of it?

**Comment by Geolykt** [comment]
yes

**Comment by Restland** [comment]
https://youtu.be/_OsZ0yhvDtg

**Comment by Geolykt** [comment]
If the latest commit didn't fix it (which is 90% likely), then it is probably an issue with another plugin not expecting that something does what we do. I guess the only "fix" there would be to disable the enchantment
