### ISSUE TITLE
Enchantment table

### ISSUE THREAD

**Issue by pokemonrocks9** [Geolykt/EnchantmentsPlus#83]
Enchantment tables do not give the enchants 
Unless using a book

**Comment by Geolykt** [comment]
Can you enchant via commands? If no, could you provide a list of datapacks your server is running on?

**Comment by pokemonrocks9** [comment]
Commands work fine as does enchanting a book. None of the items can get the enchantments though including with an anvil. Only if done with commands does it work.
We use 0 datapack only plugins

**Comment by Geolykt** [comment]
Ugh, will need to debug that one day I guess.

**Comment by Geolykt** [comment]
Similar to #94 I was also not able to reproduce this bug. And similarly there should be no reason why it does not work but similarly I have received a couple of reports in the past from this bug, so it likely isn't a user error.
Help is appreciated if someone was to know what the bug is
