### ISSUE TITLE
No level 30 Enchants

### ISSUE THREAD

**Issue by owenemo** [Geolykt/EnchantmentsPlus#86]
Hello,

I am slightly confused about how enchanting works,

How can I get normal enchants. I can't get level 30 enchants.

I get terrible vanilla enchantments on everything. Unbreaking 1, Projecticle Protection 1.

Sorry for the confusion,

Thanks,
Owen

**Comment by Geolykt** [comment]
The plugin only **supplements** the vanilla enchantment system, it does not reduce the chance of it by any means. This is likely a false posititive that occours due to the inherently random state of this system
