### ISSUE TITLE
3.0.0 Refractor Discussion Thread

### ISSUE THREAD

**Issue by Geolykt** [Geolykt/EnchantmentsPlus#9]
While Version 3.0.0 is still a few months from being reality (especially since v2.0.0 is still in development), there is still a reason to think about what should be changed in Version 3.0.0.
While v2.0.0 hasn't seem much of a removal of gameplay elements (outside of description lore - which has been fully replaced with the /ench info command) but rather removal of useless code, v3.0.0 should have an increased amount of gameplay feature removal. However it will also contain a good chunk of code removal

This issue is meant to openly discuss and suggest potential removals.

Currently planned removals:
 - ~~Removal of the feature to disable enchantments via the `/ench enable` / `/ench disable` commands. Server wide disablement should still be allowed via config~~ **This feature will probably not be axed anytime soon**
 - Removal of the `enchplus.enchant.use` permission. This would likely make the code go a lot faster than before, as currently the permission is checked around 6 times every tick every player

**Comment by Kekstastisch** [comment]
Its nice for the players to turn of, vortex or shred via commands so I would hate to see /ench disable go

**Comment by Geolykt** [comment]
I think I could make so it is integrated with the enchantment cooldown, which has performance gains and would make removing it irrelevant. How didn't I come to that Idea earlier?

**Comment by Kekstastisch** [comment]
Sorry for the late reply. I am playing on a very small server with your plugin and we have an endermen farm.
when using a sword with reaper, the endermen teleport back to the spawning platform and often die there, leaving the xp behind.

Then i searched for a way to temporarily disable reaper and found the /ench disable command
