### ISSUE TITLE
Enchant Lore & and Names

### ISSUE THREAD

**Issue by llamamonium11** [Geolykt/EnchantmentsPlus#92]
Using the plugin on 1.17.1 and the curse color displays the enchantment as the normal enchantment color also enchants don't show a lore to describe what the enchant does.

**Comment by Geolykt** [comment]
The description lore option has been removed as it was simply unmaintainable. The curse enchantment colour should still work however, no idea what went wrong there

**Comment by llamamonium11** [comment]
> The description lore option has been removed as it was simply unmaintainable. The curse enchantment colour should still work however, no idea what went wrong there

yea the color for curse it the same and the normal enchant color.

**Comment by Geolykt** [comment]
Technically the code is working as intended it just wasn't being used as the Unrepairable enchantment was not considered a curse. Since we are on this topic, should Blaze's curse be considered a curse too?
