### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by llamamonium11** [Geolykt/EnchantmentsPlus#93]
![Screenshot_1](https://user-images.githubusercontent.com/46384480/132408730-bdd5dc51-ed9a-4825-9e39-a01a4ae6daaf.png)
Using Airplane-Purpur-1.17 Jar for the server. Please Fix!

**Comment by Geolykt** [comment]
Man, you cut out the most important part of the stacktrace.
Cannot fix as I do not know what went wrong there.
