### ISSUE TITLE
Fire Enchant and Fortune Enchantment dropping excessive amounts of ingots from ores.

### ISSUE THREAD

**Issue by GentlemanCheesy** [Geolykt/EnchantmentsPlus#96]
Currently using the newest version of the plugin which I believe is 4.0.1 and came across the following issue. No errors were popping up in console either. Feel free to ask for a list of plugins I'm using! Thank you for any responses in advance!

I'm not sure why but when I mine with a pickaxe that has both fortune and fire, ores (Iron, Copper, Gold) drop too many extra ingots. I have found that with fortune 2 a single ore can drop sometimes up to 12 ingots. With fortune 3 being even worse. My suggestion would be to set it so that it works the same as fortune on diamond ore would.

Example of a pickaxe I used when testing this bug
![image](https://user-images.githubusercontent.com/68432025/136452652-b9911fa3-b8cb-4846-82a0-82944759b7ce.png)

Total of 6 broken iron ore dropped on the ground.
![image](https://user-images.githubusercontent.com/68432025/136452571-467519b7-8ef7-4b22-a69b-bdcc71021f1a.png)

**Comment by Geolykt** [comment]
Yeah, this is heavily broken. Will look into it, it is likely that spigot changed the fortune code around so we don't need to account for fortune ourselves

**Comment by GentlemanCheesy** [comment]
Any update on what is causing this? I saw you recently pushed an update, and just wanted to know if this bug was still in the process of being fixed since it still occurs in the latest version!

Thanks in advance!

**Comment by Geolykt** [comment]
Fixed.
Apparently this bug has been there since day 1 of this project (not present in upstream zenchantments though), so I'm surprised that this was the only issue that was opened regarding this bug. I don't want to know how much more of these bugs are lingering around
