### ISSUE TITLE
Unable to combine tools to transfer Enchantments

### ISSUE THREAD

**Issue by kizerk** [Geolykt/EnchantmentsPlus#97]
Hi,
When attempting to transfer an enchantment from this plugin from one tool to another in an anvil the process does not result in the enchantment being adding but the tool with it on will be consumed as if it should have been.
![Pick one](https://user-images.githubusercontent.com/62256265/136616858-f4199751-1140-4d25-b72d-320b43097735.PNG)
![Pick two](https://user-images.githubusercontent.com/62256265/136616861-9d18ba35-f931-4797-961a-d3dd5c1a014c.PNG)
![Result Pick](https://user-images.githubusercontent.com/62256265/136616859-912b3d0d-eed6-4ad7-997a-d7b3f5414b11.PNG)

I am not sure if this is a result of one of the anvil changes you made but If this is possible to fix i would love to know how.

Plugin version: 4.0.1
Paper version: git-Paper-779 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 9 version(s) behind
Changes from default and previous versions I am not sure as i am not an admin on the server but any additional information needed I can ask and maybe get

**Comment by Geolykt** [comment]
If you have access to the config files, it would be good to know whether the 1xx-anvil-merger was employed (the setting can be found in the patches.yml file).
If would also be helpfull to see if plugin realizes that the second input item has the grab enchantment. This can be seen via the `/ench info` (no arguments) command, it could very well be that the custom lore breaks it
